CREATE DATABASE alkemy_fullstack_js;

USE alkemy_fullstack_js;

-- Clients table

CREATE TABLE clients (
  ID_CLIENT int(11) NOT NULL,
  USERNAME varchar(30) NOT NULL,
  EMAIL varchar(30) NOT NULL,
  PASSWORD varchar(30) NOT NULL,
  FULLNAME varchar(30) NOT NULL,
  IS_VERIFIED tinyint(1) NOT NULL
);

-- Configurations

ALTER TABLE clients
  ADD PRIMARY KEY (ID_CLIENT),
  MODIFY ID_CLIENT int(11) NOT NULL AUTO_INCREMENT;

-- Budget table

CREATE TABLE budget (
  ID_BUDGET int(11) NOT NULL,
  INCOME int(15) NOT NULL,
  EXPENSES int(15) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ID_CLIENT int(11) NOT NULL,
  CONSTRAINT fk_budget FOREIGN KEY (ID_CLIENT) REFERENCES clients(ID_CLIENT)
);

-- Configurations

ALTER TABLE budget
  ADD PRIMARY KEY (ID_BUDGET),
  ADD UNIQUE KEY ID_CLIENT (ID_CLIENT),
  MODIFY ID_BUDGET int NOT NULL AUTO_INCREMENT;