CREATE DATABASE alkemy_fullstack_js;

USE alkemy_fullstack_js;

-- Clients table

CREATE TABLE clients (
  ID_CLIENT int(11) NOT NULL,
  USERNAME varchar(30) NOT NULL,
  EMAIL varchar(30) NOT NULL,
  PASSWORD varchar(30) NOT NULL,
  FULLNAME varchar(30) NOT NULL,
  IS_VERIFIED tinyint(1) NOT NULL
);

-- Configurations

ALTER TABLE clients
  ADD PRIMARY KEY (ID_CLIENT),
  MODIFY ID_CLIENT int(11) NOT NULL AUTO_INCREMENT;

-- Budgets table

CREATE TABLE operations (
  ID_BUDGET int(11) NOT NULL,
  INCOME int(15) NOT NULL,
  EXPENSES int(15) NOT NULL,
  CREATED_AT date NOT NULL DEFAULT (CURRENT_DATE),
  CATEGORY varchar(30),
  ID_CLIENT int(11) NOT NULL,
  CONSTRAINT fk_budget FOREIGN KEY (ID_CLIENT) REFERENCES clients(ID_CLIENT)
);

-- Configurations

ALTER TABLE operations
  ADD PRIMARY KEY (ID_BUDGET),
  MODIFY ID_BUDGET int(11) NOT NULL AUTO_INCREMENT;